# Generated by Django 5.0.3 on 2024-03-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('exam', '0004_alter_exam_options_exam_created_exam_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'etapa', 'verbose_name_plural': 'etapas'},
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='answer',
            field=models.CharField(default='-', max_length=5, verbose_name=' Respuesta'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='correct',
            field=models.CharField(default='-', max_length=5, verbose_name='Respuesta correcta'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carera'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Calificacion'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='application_date',
            field=models.DateField(verbose_name='Fecha de aplicacion'),
        ),
    ]
